# Generated by Django 4.0.5 on 2022-07-12 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(max_length=1, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id_desucento', models.IntegerField(max_length=7, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id_despacho', models.IntegerField(max_length=7, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('stock', models.IntegerField(max_length=3)),
                ('precio', models.IntegerField(max_length=6)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('apellidoPaterno', models.CharField(max_length=10)),
                ('apellidoMaterno', models.CharField(max_length=10)),
                ('contraseña', models.CharField(max_length=10)),
                ('telefono', models.IntegerField(max_length=9)),
                ('direccion', models.IntegerField(max_length=10)),
                ('comuna', models.CharField(max_length=15)),
                ('region', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.IntegerField(max_length=7, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('total_vent', models.IntegerField(max_length=200)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoria')),
                ('id_descuento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.descuento')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUser',
            fields=[
                ('id_tipoUser', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('tipoUser', models.IntegerField(max_length=30)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_historial', models.IntegerField(max_length=1, primary_key=True, serialize=False)),
                ('id_despacho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.despacho')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_despacho',
            fields=[
                ('id_estado_despacho', models.IntegerField(max_length=1, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('id_despacho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.despacho')),
            ],
        ),
        migrations.AddField(
            model_name='despacho',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.usuario'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='id_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.venta'),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.IntegerField(max_length=7, primary_key=True, serialize=False)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.usuario')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.venta')),
            ],
        ),
    ]
